### ISSUE TITLE
Add primitive in the model

### ISSUE THREAD

**Issue by s-trinh** [lagadic/visp_cao_editor#8]
The idea of this feature is to be able to create, edit and add multiple primitives (3D line, 3D face, 3D cylinder or 3D circle) before the export to a `.cao` model file.

Initially, there should be no primitive:
![add_primitive](https://cloud.githubusercontent.com/assets/8035162/26734709/548f90d2-47bf-11e7-8220-4a22b9129938.png)

By clicking on new, the UI should display the default primitive (e.g. 3D line) with default values:
![3d_line_modif](https://cloud.githubusercontent.com/assets/8035162/26734854/dbebcafa-47bf-11e7-94c2-74ce14fc7ebd.png)

A proposal is to display the list of primitives already added in a tree view box (e.g. below the current ViSP CAD Properties Panel):
![tree_view](https://cloud.githubusercontent.com/assets/8035162/26735027/8aaf4940-47c0-11e7-827c-53d829fc336c.png)

**Comment by vikasTmz** [comment]
I'm a little confused to why this tree view box is needed. As in the features introduced in #11, #12, #13 are already achieved in the current implementation. Since object(s) have to be selected eventually to be able to associate primitives to them or export them I think the scene object tree view on the top right can be used for the above purposes. 

So to add/ edit primitives for object(s), select the object(s) and choose the primitive on the left panel. I could display the current primitive settings if any.

Since objects have to be selected on exporting, thus there wouldn't be a need to remove/ disable a primitive as they will be ignored.

**Comment by s-trinh** [comment]
Our motivations (based on our understanding of the current plugin):

- in the current plugin version, we did not manage to export multiple primitives to a `.cao` (the test case was a project with a circle and a cylinder, select the circle, edit mode, complete the circles fields, press set properties and do the same thing with the cylinder), only the last primitive was exported
- in complex CAD models we have, the object is not decomposed of multiple primitives in the object tree view and we don't want to force the user to prefilter and/or group each primitive in a specific group
- we need a (visual) feedback for the **Set Properties** button to understand what has already been added or the purpose of the button

We propose a tree view that lists all the primitives already added but it can be something else. The tree view was chosen as we thought it could be use, somehow, for the hierarchical `.cao` export but it can be changed (it can be simply a list of primitives already added for example).

**Comment by vikasTmz** [comment]
> in the current plugin version, we did not manage to export multiple primitives to a .cao ...... only the last primitive was exported

Were both the objects selected before exporting? The current implementation exports those objects that were selected before clicking `File -> Export -> Visp (.cao)`

**Comment by s-trinh** [comment]
Done in #16
